import pandas as pd
import numpy as np

def run_epic_3():
    print("--- Epic 3: Data Pre-Processing ---")
    
    # Load the datasets generated in Epic 1
    print("Loading datasets...")
    app_df = pd.read_csv('application_record.csv')
    credit_df = pd.read_csv('credit_record.csv')
    
    # Story 1: Identify and remove duplicate records
    print(f"\nStory 1: Identifying and removing duplicates...")
    initial_app_len = len(app_df)
    app_df = app_df.drop_duplicates()
    print(f"Removed {initial_app_len - len(app_df)} duplicates from applicant details.")
    
    initial_credit_len = len(credit_df)
    credit_df = credit_df.drop_duplicates()
    print(f"Removed {initial_credit_len - len(credit_df)} duplicates from credit records.")
    
    # Story 2: Detect and handle missing values
    print("\nStory 2: Detecting and handling missing values...")
    missing_app = app_df.isnull().sum().sum()
    missing_credit = credit_df.isnull().sum().sum()
    print(f"Missing values found - Applicant Details: {missing_app}, Credit Records: {missing_credit}")
    
    if missing_app > 0:
        app_df = app_df.fillna(method='ffill')  # Forward fill as an example strategy
    if missing_credit > 0:
        credit_df = credit_df.fillna('X')
        
    # Story 3 & 4: Data cleaning, merging, and feature engineering
    print("\nStory 3 & 4: Data cleaning, merging, and feature engineering...")
    # The credit record has multiple months of history for each applicant.
    # We will determine the "risk" level. In standard datasets:
    # 'C' (Paid off), 'X' (No loan) -> Good (0)
    # '0', '1', '2', '3', '4', '5' (Overdue) -> High Risk (1)
    
    print("Creating target variable 'Is_High_Risk' based on credit payment status...")
    credit_df['Risk'] = credit_df['STATUS'].apply(lambda x: 1 if x in ['0', '1', '2', '3', '4', '5'] else 0)
    
    # Aggregate credit records by applicant ID to see if they ever had a high-risk status
    applicant_risk = credit_df.groupby('ID')['Risk'].max().reset_index()
    applicant_risk.rename(columns={'Risk': 'Is_High_Risk'}, inplace=True)
    
    # Merge the application details with the risk label
    print("Merging demographic information with credit status records...")
    merged_df = pd.merge(app_df, applicant_risk, on='ID', how='inner')
    print(f"Total merged records: {len(merged_df)}")
    
    # Additional feature engineering: convert Days Birth and Days Employed to Years
    merged_df['Age_Years'] = np.abs(merged_df['DAYS_BIRTH']) / 365.25
    merged_df['Years_Employed'] = np.where(merged_df['DAYS_EMPLOYED'] > 0, 0, np.abs(merged_df['DAYS_EMPLOYED']) / 365.25)
    merged_df.drop(['DAYS_BIRTH', 'DAYS_EMPLOYED', 'ID'], axis=1, inplace=True)
    
    # Story 5: Convert categorical variables into numerical representations
    print("\nStory 5: Converting categorical variables to numerical representations...")
    categorical_columns = ['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 
                           'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 
                           'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE']
                           
    # Using Pandas get_dummies for One-Hot Encoding
    processed_df = pd.get_dummies(merged_df, columns=categorical_columns, drop_first=True)
    
    # Ensure boolean columns generated by get_dummies are converted to integers (0 or 1)
    for col in processed_df.columns:
        if processed_df[col].dtype == bool:
            processed_df[col] = processed_df[col].astype(int)
            
    print(f"Final dataset shape after pre-processing: {processed_df.shape}")
    
    # Save the cleaned and processed dataset for Model Building (Epic 4)
    processed_df.to_csv('processed_dataset.csv', index=False)
    print("Processed dataset saved as 'processed_dataset.csv'. Epic 3 completed successfully!")

if __name__ == "__main__":
    run_epic_3()
